apiVersion: apps/v1
kind: Deployment
metadata:
  name: container-two
spec:
  replicas: 1
  selector:
    matchLabels:
      app: container-two
  template:
    metadata:
      labels:
        app: container-two
    spec:
      containers:
        - name: container-two
          image: gcr.io/$PROJECT_ID/container-two:$COMMIT_SHA
          ports:
            - containerPort: 6001
          volumeMounts:
            - mountPath: "/bhishman_PV_dir"
              name: volume
      volumes:
        - name: volume
          persistentVolumeClaim:
            claimName: pv-claim

---
apiVersion: v1
kind: Service
metadata:
  name: service-two
spec:
  selector:
    app: container-two
  ports:
    - protocol: TCP
      port: 6001
      targetPort: 6001
  type: LoadBalancer